name: Disparo Diario WhatsApp

on:
  schedule:
    # 08:00 Horário de Brasília (11:00 UTC), de segunda a sábado (1 a 6)
    - cron: '0 11 * * 1-6'
  workflow_dispatch:

jobs:
  enviar-mensagem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Executar Script
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          EVOLUTION_API_URL: ${{ secrets.EVOLUTION_API_URL }}
          EVOLUTION_INSTANCE: ${{ secrets.EVOLUTION_INSTANCE }}
          EVOLUTION_API_KEY: ${{ secrets.EVOLUTION_API_KEY }}
          WHATSAPP_NUMERO: ${{ secrets.WHATSAPP_NUMERO }}
        run: node enviar_resumo.js
