name: Relatorio Operacoes (08h-18h)

on:
  schedule:
    - cron: '0 11-21 * * 1-6' # Segunda a Sábado, de 1 em 1 hora, das 08:00 às 18:00 Brasília (UTC-3)
  workflow_dispatch:

jobs:
  enviar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Executar Script
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          EVOLUTION_API_URL: ${{ secrets.EVOLUTION_API_URL }}
          EVOLUTION_INSTANCE: ${{ secrets.EVOLUTION_INSTANCE }}
          EVOLUTION_API_KEY: ${{ secrets.EVOLUTION_API_KEY }}
          WHATSAPP_NUMERO: ${{ secrets.WHATSAPP_NUMERO }}
        run: node enviar_operacoes.js
